In [74]:
import numpy as np

In [75]:
def init_pop(pop_size):
    return np.random.randint(8, size=(pop_size,8))

In [76]:
initial_population = init_pop(4)
print(initial_population)

[[6 3 6 1 1 4 5 1]
 [1 2 3 3 0 5 1 2]
 [2 5 4 1 4 5 6 7]
 [0 3 2 3 0 1 4 5]]


In [77]:
def calc_fitness(population):
    fitness_vals=[]
    for x in population:
        penalty = 0
        for i in range(8):
            r=x[i]
            for j in range(8):
                if i==j:
                     d = abs(i-j)
                if x[j] in [r,r-d, r+d]:
                    penalty += 1
                    fitness_vals.append(penalty)
        return -1*np.array(fitness_vals)
                    
                    

In [78]:
fitness_vals= calc_fitness(initial_population)
print(fitness_vals)

[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16]


In [84]:
def selection(population, fitness_vals):
    probs = fitness_vals.copy()
    probs += abs(probs.min())+1
    probs = probs/ probs.sum()
    N = len(population)
    indices = np.arange(N)
    selected_indices= np.random.choice(indices,size=N, p=probs)
    selected_population = population[selected_indices]
    return selected_population


In [85]:
selected_population= selection(initial_population, fitness_vals)
print(selected_population)

ValueError: 'a' and 'p' must have same size

In [98]:

#initialize population
import random
best=-100000
populations =([[random.randint(0,1) for x in range(6)] for i in range(4)])
print(type(populations))
parents=[]
new_populations = []
print(populations)

<class 'list'>
[[0, 1, 0, 1, 1, 0], [1, 0, 1, 0, 0, 0], [1, 1, 1, 0, 0, 0], [1, 1, 1, 0, 0, 0]]


In [99]:
#fitness score calculation ............
def fitness_score() :
    global populations,best
    fit_value = []
    fit_score=[]
    for i in range(4) :
        chromosome_value=0
        
        for j in range(5,0,-1) :
            chromosome_value += populations[i][j]*(2**(5-j))
        chromosome_value = -1*chromosome_value if populations[i][0]==1 else chromosome_value
        print(chromosome_value)
        fit_value.append(-(chromosome_value**2) + 5 )
    print(fit_value)
    fit_value, populations = zip(*sorted(zip(fit_value, populations) , reverse = True))
    best= fit_value[0]
    
fitness_score()

22
-8
-24
-24
[-479, -59, -571, -571]


In [100]:
def selectparent():
    global parents
    #global populations , parents
    parents=populations[0:2]
    print(type(parents))
    print(parents)
selectparent()


<class 'tuple'>
([1, 0, 1, 0, 0, 0], [0, 1, 0, 1, 1, 0])


In [101]:
def crossover() :
    global parents
    
    cross_point = random.randint(0,5)
    parents=parents + tuple([(parents[0][0:cross_point +1] +parents[1][cross_point+1:6])])
    parents =parents+ tuple([(parents[1][0:cross_point +1] +parents[0][cross_point+1:6])])
    
    print(parents)

In [102]:
def mutation() :
    global populations, parents
    mute = random.randint(0,49)
    if mute == 20 :
        x=random.randint(0,3)
        y = random.randint(0,5)
        parents[x][y] = 1-parents[x][y]
    populations = parents
    print(populations)

In [106]:
for i in range(5) :
    fitness_score()
    selectparent() 
    crossover()
    mutation()
print("best score :")
print(best)
print("sequence........")
print(populations[0])
    

-6
6
-6
-6
[-31, -31, -31, -31]
<class 'tuple'>
([1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0])
([1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0])
([1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 0, 1, 0])
-6
-6
-6
-2
[-31, -31, -31, 1]
<class 'tuple'>
([1, 0, 0, 0, 1, 0], [1, 0, 0, 1, 1, 0])
([1, 0, 0, 0, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 0, 1, 0])
([1, 0, 0, 0, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0], [1, 0, 0, 0, 1, 0])
-2
-6
-6
-2
[1, -31, -31, 1]
<class 'tuple'>
([1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0])
([1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0])
([1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0])
-2
-2
-2
-2
[1, 1, 1, 1]
<class 'tuple'>
([1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0])
([1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0])
([1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0], [1, 0, 0, 0, 1, 0])
-2
-2
-